# Generated by Django 3.2.5 on 2021-08-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='/imgs/user.png', upload_to=''),
        ),
    ]
